# fly.toml app configuration file generated for werewolf-arena on 2025-11-01T20:09:40+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'werewolf-arena'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEBUG = 'false'
  ENVIRONMENT = 'production'
  NODE_ENV = 'production'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
